/**
 *  @file This file contains all enums of AnimeKitsu and MangaKitsu method, can be exported for other purpose.
 */

/**
 * @enum
 * @description This enum contain all of manga categories that use Kitsu.app
 * @since 1.3.0
 */
enum EKitsuMangaCategories {
  VIOLENCE = "violence",
  PLOT_CONTINUITY = "plot_continuity",
  STEREOTYPES = "stereotypes",
  TONE_CHANGES = "tone_changes",
  ACTION = "action",
  BATTLE_ROYALE = "battle_royale",
  GUNFIGHTS = "gunfights",
  NINJA = "ninja",
  SPACE_BATTLES = "space_battles",
  SAMURAI = "samurai",
  ADVENTURE = "adventure",
  ANGST = "angst",
  ANIME_INFLUENCED = "anime_influenced",
  ANTHROPOMORPHISM = "anthropomorphism",
  BLACKMAIL = "blackmail",
  ABSURDIST_HUMOUR = "absurdist_humour",
  BREAKING_THE_FOURTH_WALL = "breaking_the_fourth_wall",
  PARODY = "parody",
  SATIRE = "satire",
  VIOLENT_RETRIBUTION_FOR_ACCIDENTAL_INFRINGEMENT = "violent_retribution_for_accidental_infringement",
  SUPER_DEFORMED = "super_deformed",
  DETECTIVE = "detective",
  DRAMA = "drama",
  ANGEL = "angel",
  CONTEMPORARY_FANTASY = "contemporary_fantasy",
  DARK_FANTASY = "dark_fantasy",
  DEITY = "deity",
  DEMON = "demon",
  DRAGON = "dragon",
  ELF = "elf",
  HIGH_FANTASY = "high_fantasy",
  MAGIC = "magic",
  MERMAID = "mermaid",
  GHOST = "ghost",
  HAREM = "harem",
  HENSHIN = "henshin",
  HORROR = "horror",
  MAGICAL_GIRL = "magical_girl",
  MYSTERY = "mystery",
  PARASITE = "parasite",
  DEMENTIA = "dementia",
  PSYCHOLOGICAL = "psychological",
  LOVE_POLYGON = "love_polygon",
  SHOUJO_AI = "shoujo_ai",
  SHOUNEN_AI = "shounen_ai",
  SLOW_WHEN_IT_COMES_TO_LOVE = "slow_when_it_comes_to_love",
  SUDDEN_GIRLFRIEND_APPEARANCE = "sudden_girlfriend_appearance",
  UNREQUITED_LOVE = "unrequited_love",
  SCIENCE_FICTION = "science_fiction",
  HUMANOID_ALIEN = "humanoid_alien",
  CYBERPUNK = "cyberpunk",
  CYBORG = "cyborg",
  GENETIC_MODIFICATION = "genetic_modification",
  POWER_SUIT = "power_suit",
  ANDROID = "android",
  PILOTED_ROBOT = "piloted_robot",
  ROBOT_HELPER = "robot_helper",
  SUPER_ROBOT = "super_robot",
  TRANSFORMING_CRAFT = "transforming_craft",
  SPACE_OPERA = "space_opera",
  SPACE_TRAVEL = "space_travel",
  STEAMPUNK = "steampunk",
  TIME_TRAVEL = "time_travel",
  SUPERHERO = "superhero",
  SUPERNATURAL = "supernatural",
  THRILLER = "thriller",
  VAMPIRE = "vampire",
  VIRTUAL_REALITY = "virtual_reality",
  ZOMBIE = "zombie",
  COUNTRYSIDE = "countryside",
  DESERT = "desert",
  AFRICA = "africa",
  UNITED_STATES = "united_states",
  NEW_YORK = "new_york",
  AMERICAS = "americas",
  EARTH = "earth",
  SUPER_POWER = "super_power",
  MECHA = "mecha",
  ROBOT = "robot",
  ALIEN = "alien",
  ROMANCE = "romance",
  ASIA = "asia",
  CHINA = "china",
  JAPAN = "japan",
  KYOTO = "kyoto",
  TOKYO = "tokyo",
  KOREA = "korea",
  FRANCE = "france",
  EUROPE = "europe",
  ITALY = "italy",
  GERMANY = "germany",
  RUSSIA = "russia",
  UNITED_KINGDOM = "united_kingdom",
  MIDDLE_EAST = "middle_east",
  FANTASY_WORLD = "fantasy_world",
  FLOATING_ISLAND = "floating_island",
  FUTURE = "future",
  ISEKAI = "isekai",
  ISLAND = "island",
  PARALLEL_UNIVERSE = "parallel_universe",
  ALTERNATIVE_PAST = "alternative_past",
  BAKUMATSU_MEIJI_PERIOD = "bakumatsu_meiji_period",
  HEIAN_PERIOD = "heian_period",
  SENGOKU_PERIOD = "sengoku_period",
  THREE_KINGDOMS = "three_kingdoms",
  TOKUGAWA_PERIOD = "tokugawa_period",
  VICTORIAN_PERIOD = "victorian_period",
  WORLD_WAR_II = "world_war_ii",
  HISTORICAL = "historical",
  PAST = "past",
  PRESENT = "present",
  ALTERNATIVE_PRESENT = "alternative_present",
  OTHER_PLANET = "other_planet",
  SHIPBOARD = "shipboard",
  MARS = "mars",
  SPACE = "space",
  SUMMER = "summer",
  JOSEI = "josei",
  KIDS = "kids",
  SEINEN = "seinen",
  SHOUJO = "shoujo",
  SHOUNEN = "shounen",
  ANTI_WAR = "anti_war",
  COMING_OF_AGE = "coming_of_age",
  CONSPIRACY = "conspiracy",
  COOKING = "cooking",
  ASSASSIN = "assassin",
  BOUNTY_HUNTER = "bounty_hunter",
  MAFIA = "mafia",
  PIRATE = "pirate",
  THIEVERY = "thievery",
  EPIDEMIC = "epidemic",
  POST_APOCALYPSE = "post_apocalypse",
  WAR = "war",
  FAMILY = "family",
  FRIENDSHIP = "friendship",
  GENDER_BENDER = "gender_bender",
  COPS = "cops",
  SHINSENGUMI = "shinsengumi",
  AIR_FORCE = "air_force",
  FEUDAL_WARFARE = "feudal_warfare",
  NAVY = "navy",
  MILITARY = "military",
  SPECIAL_SQUADS = "special_squads",
  LAW_AND_ORDER = "law_and_order",
  DISASTER = "disaster",
  NETORARE = "netorare",
  PARENTAL_ABANDONMENT = "parental_abandonment",
  POLITICS = "politics",
  PROXY_BATTLES = "proxy_battles",
  BUDDHISM = "buddhism",
  REVENGE = "revenge",
  ROTTEN_WORLD = "rotten_world",
  DYSTOPIA = "dystopia",
  SCHOOL_LIFE = "school_life",
  ALL_GIRLS_SCHOOL = "all_girls_school",
  DELINQUENT = "delinquent",
  ELEMENTARY_SCHOOL = "elementary_school",
  HIGH_SCHOOL = "high_school",
  MIDDLE_SCHOOL = "middle_school",
  SCHOOL_CLUBS = "school_clubs",
  STUDENT_GOVERNMENT = "student_government",
  UNIVERSITY = "university",
  RELIGION = "religion",
  SLAVERY = "slavery",
  SLICE_OF_LIFE = "slice_of_life",
  WORKING_LIFE = "working_life",
  BASEBALL = "baseball",
  BASKETBALL = "basketball",
  SPORTS = "sports",
  CARD_GAMES = "card_games",
  COMBAT = "combat",
  CYCLING = "cycling",
  BOXING = "boxing",
  WRESTLING = "wrestling",
  MOTORSPORT = "motorsport",
  DRIFTING = "drifting",
  FORMULA_RACING = "formula_racing",
  STREET_RACING = "street_racing",
  SOCCER = "soccer",
  TENNIS = "tennis",
  VOLLEYBALL = "volleyball",
  IDOL = "idol",
  MUSICAL_BAND = "musical_band",
  PERFORMANCE = "performance",
  THE_ARTS = "the_arts",
  FANTASY = "fantasy",
  ECCHI = "ecchi",
  HUMAN_ENHANCEMENT = "human_enhancement",
  CRIME = "crime",
  MUSIC = "music",
}

/**
 * @enum
 * @description This enum contain all of anime categories that use Kitsu.app
 * @since 1.3.0
 */

enum EKitsuAnimeCategories {
  VIOLENCE = "violence",
  PLOT_CONTINUITY = "plot_continuity",
  STEREOTYPES = "stereotypes",
  TONE_CHANGES = "tone_changes",
  ACTION = "action",
  BATTLE_ROYALE = "battle_royale",
  GUNFIGHTS = "gunfights",
  MARTIAL_ARTS = "martial_arts",
  NINJA = "ninja",
  SPACE_BATTLES = "space_battles",
  SWORDPLAY = "swordplay",
  SAMURAI = "samurai",
  ADVENTURE = "adventure",
  ANGST = "angst",
  ANIME_INFLUENCED = "anime_influenced",
  ANTHROPOMORPHISM = "anthropomorphism",
  BLACKMAIL = "blackmail",
  COMEDY = "comedy",
  ABSURDIST_HUMOUR = "absurdist_humour",
  BREAKING_THE_FOURTH_WALL = "breaking_the_fourth_wall",
  PARODY = "parody",
  SATIRE = "satire",
  SUPER_DEFORMED = "super_deformed",
  VIOLENT_RETRIBUTION_FOR_ACCIDENTAL_INFRINGEMENT = "violent_retribution_for_accidental_infringement",
  DETECTIVE = "detective",
  DRAMA = "drama",
  FANTASY = "fantasy",
  ANGEL = "angel",
  CONTEMPORARY_FANTASY = "contemporary_fantasy",
  DARK_FANTASY = "dark_fantasy",
  DEITY = "deity",
  DEMON = "demon",
  DRAGON = "dragon",
  ELF = "elf",
  HIGH_FANTASY = "high_fantasy",
  MAGIC = "magic",
  MERMAID = "mermaid",
  GHOST = "ghost",
  HAREM = "harem",
  HENSHIN = "henshin",
  HORROR = "horror",
  MAGICAL_GIRL = "magical_girl",
  MYSTERY = "mystery",
  PARASITE = "parasite",
  DEMENTIA = "dementia",
  LOVE_POLYGON = "love_polygon",
  PSYCHOLOGICAL = "psychological",
  ROMANCE = "romance",
  SHOUJO_AI = "shoujo_ai",
  SHOUNEN_AI = "shounen_ai",
  SLOW_WHEN_IT_COMES_TO_LOVE = "slow_when_it_comes_to_love",
  SUDDEN_GIRLFRIEND_APPEARANCE = "sudden_girlfriend_appearance",
  UNREQUITED_LOVE = "unrequited_love",
  ECCHI = "ecchi",
  SLAPSTICK = "slapstick",
  SCIENCE_FICTION = "science_fiction",
  ALIEN = "alien",
  HUMANOID_ALIEN = "humanoid_alien",
  CYBERPUNK = "cyberpunk",
  HUMAN_ENHANCEMENT = "human_enhancement",
  CYBORG = "cyborg",
  GENETIC_MODIFICATION = "genetic_modification",
  MECHA = "mecha",
  ROBOT = "robot",
  POWER_SUIT = "power_suit",
  SPACE_OPERA = "space_opera",
  SPACE_TRAVEL = "space_travel",
  STEAMPUNK = "steampunk",
  TIME_TRAVEL = "time_travel",
  SUPER_POWER = "super_power",
  SUPERHERO = "superhero",
  SUPERNATURAL = "supernatural",
  THRILLER = "thriller",
  VAMPIRE = "vampire",
  ZOMBIE = "zombie",
  VIRTUAL_REALITY = "virtual_reality",
  COUNTRYSIDE = "countryside",
  DESERT = "desert",
  EARTH = "earth",
  AFRICA = "africa",
  AMERICAS = "americas",
  UNITED_STATES = "united_states",
  NEW_YORK = "new_york",
  CHINA = "china",
  JAPAN = "japan",
  KYOTO = "kyoto",
  TOKYO = "tokyo",
  EUROPE = "europe",
  KOREA = "korea",
  MIDDLE_EAST = "middle_east",
  FRANCE = "france",
  GERMANY = "germany",
  ITALY = "italy",
  RUSSIA = "russia",
  UNITED_KINGDOM = "united_kingdom",
  FLOATING_ISLAND = "floating_island",
  FANTASY_WORLD = "fantasy_world",
  FUTURE = "future",
  ISEKAI = "isekai",
  ISLAND = "island",
  PARALLEL_UNIVERSE = "parallel_universe",
  PAST = "past",
  ALTERNATIVE_PAST = "alternative_past",
  BAKUMATSU_MEIJI_PERIOD = "bakumatsu_meiji_period",
  HEIAN_PERIOD = "heian_period",
  SENGOKU_PERIOD = "sengoku_period",
  THREE_KINGDOMS = "three_kingdoms",
  TOKUGAWA_PERIOD = "tokugawa_period",
  VICTORIAN_PERIOD = "victorian_period",
  WORLD_WAR_II = "world_war_ii",
  HISTORICAL = "historical",
  PRESENT = "present",
  ALTERNATIVE_PRESENT = "alternative_present",
  SPACE = "space",
  OTHER_PLANET = "other_planet",
  MARS = "mars",
  SHIPBOARD = "shipboard",
  SUMMER = "summer",
  JOSEI = "josei",
  KIDS = "kids",
  SEINEN = "seinen",
  SHOUJO = "shoujo",
  SHOUNEN = "shounen",
  ANTI_WAR = "anti_war",
  COMING_OF_AGE = "coming_of_age",
  CONSPIRACY = "conspiracy",
  COOKING = "cooking",
  CRIME = "crime",
  ASSASSIN = "assassin",
  BOUNTY_HUNTER = "bounty_hunter",
  MAFIA = "mafia",
  PIRATE = "pirate",
  THIEVERY = "thievery",
  DISASTER = "disaster",
  EPIDEMIC = "epidemic",
  POST_APOCALYPSE = "post_apocalypse",
  WAR = "war",
  FAMILY = "family",
  FRIENDSHIP = "friendship",
  GENDER_BENDER = "gender_bender",
  LAW_AND_ORDER = "law_and_order",
  COPS = "cops",
  SPECIAL_SQUADS = "special_squads",
  SHINSENGUMI = "shinsengumi",
  MILITARY = "military",
  AIR_FORCE = "air_force",
  FEUDAL_WARFARE = "feudal_warfare",
  NAVY = "navy",
  NETORARE = "netorare",
  PARENTAL_ABANDONMENT = "parental_abandonment",
  POLITICS = "politics",
  PROXY_BATTLES = "proxy_battles",
  RELIGION = "religion",
  BUDDHISM = "buddhism",
  REVENGE = "revenge",
  DYSTOPIA = "dystopia",
  SCHOOL_LIFE = "school_life",
  MUSIC = "music",
}
/**
 * @enum
 * @description This enum contain the basic seasons of the year.
 * @since 1.3.0
 */
enum EKitsuSeason {
  Spring = "spring",
  Summer = "summer",
  Fall = "fall",
  Autumn = Fall,
  Winter = "winter",
}

/**
 * @enum
 * @description This enum contain all of streamers that is available.
 * @since 1.3.0
 */
enum EKitsuAnimeStreamers {
  Crunchyroll = "Crunchyroll",
  Hulu = "Hulu",
  Funanimation = "Funanimation",
  ConTV = "CONtv",
  Netflix = "Netflix",
  Hidive = "HIDIVE",
  TubiTV = "TubiTV",
  Amazon = "Amazon",
  Youtube = "Youtube",
  AnimeLab = "AnimeLab",
  VRV = "VRV",
}

/**
 * @enum
 * @description This enum contain all of age rating categories that use Kitsu.app
 * @since 1.3.0
 */
enum EKitsuAnimeAgeRating {
  G = "G",
  PG = "PG",
  R = "R",
  ParentalGuidanceSuggested = PG,
  GeneralAudience = G,
  Restricted = R,
}

/**
 * @enum
 * @description This enum contain all of anime sub types categories that use Kitsu.app
 * @since 1.3.0
 */
enum EKitsuAnimeSubTypes {
  ONA = "ONA",
  OVA = "OVA",
  TV = "TV",
  Movie = "movie",
  Music = "music",
  Special = "Special",
}

/**
 * @enum
 * @description This enum contain all of manga sub types categories that use Kitsu.app
 * @since 1.3.0
 */
enum EKitsuMangaSubTypes {
  manga = "manga",
  Roman = "roman",
  Manhua = "manhua",
  Manhwa = "manhwa",
  OneShot = "oneshot",
  Doujin = "doujin",
  AmeriManga = "oel",
}

export {
  EKitsuAnimeAgeRating,
  EKitsuAnimeCategories,
  EKitsuAnimeStreamers,
  EKitsuAnimeSubTypes,
  EKitsuMangaCategories,
  EKitsuMangaSubTypes,
  EKitsuSeason,
};
